name: Build Web and Deploy

on:
  push:
    branches:
      - master
    paths:
      - apps/web/**
      - package.json
      - workspace.json
      - .github/workflows/**

jobs:
  web-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
            node-version: "14"
      - name: Lint and Build
        run: |
          npm ci
          npm run lint -- web
          npm run build -- web --prod --baseHref=/cryptobank-api/
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/web
