name: Build and Deploy

on:
  push:
    branches:
      - master
    paths:
      - apps/api/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
            node-version: "14"
      - name: Lint and Build
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cryptobank-test-api"
          heroku_email: "valburyakov@gmail.com"
          usedocker: true
